pipeline {


agent {
    label 'k8s-master'
}

options {
    timestamps()
    disableConcurrentBuilds()
}
 environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub'
        DOCKER_IMAGE = 'nirav1611/smsf-app'
    }


stages {

    stage('Preparation') {
        steps {
            cleanWs()
        }
    }

    stage('Checkout') {
        steps {
            git branch: 'master',
                credentialsId: 'gitid',
                url: 'https://github.com/desainiravp/smsf.git'
        }
    }

    stage('Build Docker Image') {
    steps {
        sh """
        docker build -t ${DOCKER_IMAGE}:latest ./app
        """
    }
}

    stage('Docker Login') {
        steps {
            withCredentials([usernamePassword(
                credentialsId: 'dockerhub',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )]) {
                sh '''
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                '''
            }
        }
    }

   stage('Push Image') {
    steps {
        sh """
        docker push ${DOCKER_IMAGE}:latest
        """
    }
}

    stage('Deploy to Kubernetes') {
            steps {
                sh """
                kubectl apply -f ./k8s 
                 kubectl rollout restart deployment smsf-app -n smsf
                 kubectl rollout status deployment smsf-app -n smsf
                """
            }
        }

}
}


